[package]
name = "webserver"
version = "0.1.0"
authors = ["ArneVanDongen <Arne.vdongen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse = "1.4.1"
